CREATE TABLE ADDRESS (ID BIGINT NOT NULL, CITY VARCHAR(255), COUNTRY VARCHAR(255), STREET1 VARCHAR(255), ZIPCODE VARCHAR(255), PRIMARY KEY (ID)) engine=InnoDB
CREATE TABLE CUSTOMER (ID BIGINT NOT NULL, AGE INTEGER, EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), GENDER VARCHAR(255), LASTNAME VARCHAR(255), address_fk BIGINT NOT NULL, PRIMARY KEY (ID)) engine=InnoDB
CREATE TABLE BOOK (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), ILLUSTRATIONS TINYINT(1) default 0, ISBN VARCHAR(255), NBOFPAGE INTEGER, PRICE FLOAT, TITLE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) engine=InnoDB
CREATE TABLE CD (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), PRICE FLOAT, TITLE VARCHAR(255), PRIMARY KEY (ID)) engine=InnoDB
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_address_fk FOREIGN KEY (address_fk) REFERENCES ADDRESS (ID)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) engine=InnoDB
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
